### ISSUE TITLE
Добавление сущности - Задача (таска)

### ISSUE THREAD

**Issue by FrediKats** [kysect/Recademy#42]
Реализовать концепцию задач - задания, которые формирует ментор, которые связаны с какими-то технологиями и подразумевают заливание решений студентами. В последствии ментор оценивает эти решения.
Задачи:
- [ ] Реализовать хранение информации о тасках #37 
- [ ] Реализовать возможность создавать таску #38  
- [ ] Добавление проекта под таску #39  
- [ ] Реализовать оценивание решения таски #40  
- [ ] Реализация поиска задач #41

**Comment by annchous** [comment]
Пока из кейсов использования придумали вариант "домашки в Академии".
